
name: Build Deb Package

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  release:
    types: ["published"]
jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build Debian Package in Docker
        run: |
          docker run --rm -v $(pwd):/tmp debian:bookworm-slim bash -c \
          "cd /tmp \
          && chmod 555 homeassistant-supervised/DEBIAN/p* \
          && dpkg-deb --build --root-owner-group homeassistant-supervised"
      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: homeassistant-supervised.deb
          path: homeassistant-supervised.deb
